# Generated by Django 4.1 on 2022-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=65, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=65, unique=True)),
                ('department', models.CharField(choices=[('COMPUTER SCIENCE', 'COMPUTER SCIENCE'), ('MATHEMATICS & STATISTICS', 'MATHEMATICS & STATISTICS'), ('COMPUTER INFO SYSTEM', 'COMPUTER INFO SYSTEM')], default='COMPUTER SCIENCE', max_length=65)),
                ('course1', models.CharField(blank=True, choices=[('DATA STRUCTURES & ALGORITHM', 'DATA STRUCTURES & ALGORITHM'), ('INTRODUCTION TO DATA SCIENCE', 'INTRODUCTION TO DATA SCIENCE'), ('ARTIFICIAL INTELLIGENCE', 'ARTIFICIAL INTELLIGENCE'), ('ANALYTICS', 'ANALYTICS')], default='ANALYTICS', max_length=65, null=True)),
                ('course2', models.CharField(blank=True, choices=[('DATA STRUCTURES & ALGORITHM', 'DATA STRUCTURES & ALGORITHM'), ('INTRODUCTION TO DATA SCIENCE', 'INTRODUCTION TO DATA SCIENCE'), ('ARTIFICIAL INTELLIGENCE', 'ARTIFICIAL INTELLIGENCE'), ('ANALYTICS', 'ANALYTICS')], default='ANALYTICS', max_length=65, null=True)),
                ('course3', models.CharField(blank=True, choices=[('DATA STRUCTURES & ALGORITHM', 'DATA STRUCTURES & ALGORITHM'), ('INTRODUCTION TO DATA SCIENCE', 'INTRODUCTION TO DATA SCIENCE'), ('ARTIFICIAL INTELLIGENCE', 'ARTIFICIAL INTELLIGENCE'), ('ANALYTICS', 'ANALYTICS')], default='ANALYTICS', max_length=65, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
