# Generated by Django 4.1 on 2022-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_quizcreate_option5'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcreate',
            name='answer',
            field=models.CharField(default='option1', max_length=500),
        ),
    ]
