# Generated by Django 4.1 on 2022-09-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quizcreate_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(db_index=True, max_length=265)),
                ('slug', models.SlugField(max_length=265, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.AlterField(
            model_name='quizcreate',
            name='course_name',
            field=models.ForeignKey(default='', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='quizapp.course'),
        ),
        migrations.AlterField(
            model_name='quizstudent',
            name='quiz_course',
            field=models.ForeignKey(default='', max_length=256, on_delete=django.db.models.deletion.CASCADE, to='quizapp.course'),
        ),
    ]
