# Generated by Django 4.1 on 2022-09-14 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_course_alter_quizcreate_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstudent',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizstudent',
            name='time_taken',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
