# Generated by Django 4.1 on 2023-06-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_quizstudent_score_quizstudent_time_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizstudent',
            name='department',
        ),
    ]
